sudo: false
language: node_js
node_js:
  - 8
  - 10
  - node
script:
  - npm install
  - npm run lint
  - npm test
before_deploy: 'npm run prepublishOnly'
deploy:
  provider: npm
  api_key: $NPM_TOKEN
  email: $NPM_EMAIL
  on:
    branch: master
  skip_cleanup: true
notifications:
  email:
    on_success: never
    on_failure: always
